/* This file is generated by scripts/generate-platform-graphics.mjs. */

export type LumenIllustrationToneRole = 'accent' | 'brand' | 'danger' | 'ink-muted' | 'success'

export type LumenIllustrationElement =
  | { readonly cx: number, readonly cy: number, readonly kind: 'circle', readonly r: number }
  | { readonly kind: 'line' | 'polygon' | 'polyline', readonly points: readonly number[] }
  | { readonly height: number, readonly kind: 'rounded-rect', readonly radius: number, readonly width: number, readonly x: number, readonly y: number }

export const lumenIllustrations = {
  "empty": {
    "elements": [
      {
        "kind": "polygon",
        "points": [
          32,
          48,
          88,
          48,
          81,
          83,
          39,
          83
        ]
      },
      {
        "kind": "polyline",
        "points": [
          43,
          48,
          49,
          36,
          71,
          36,
          77,
          48
        ]
      },
      {
        "kind": "line",
        "points": [
          47,
          66,
          73,
          66
        ]
      }
    ],
    "semanticTone": "brand"
  },
  "success": {
    "elements": [
      {
        "cx": 60,
        "cy": 60,
        "kind": "circle",
        "r": 28
      },
      {
        "kind": "polyline",
        "points": [
          45,
          60,
          55,
          70,
          76,
          47
        ]
      }
    ],
    "semanticTone": "success"
  },
  "error": {
    "elements": [
      {
        "cx": 60,
        "cy": 60,
        "kind": "circle",
        "r": 28
      },
      {
        "kind": "line",
        "points": [
          49,
          49,
          71,
          71
        ]
      },
      {
        "kind": "line",
        "points": [
          71,
          49,
          49,
          71
        ]
      }
    ],
    "semanticTone": "danger"
  },
  "offline": {
    "elements": [
      {
        "height": 35,
        "kind": "rounded-rect",
        "radius": 18,
        "width": 72,
        "x": 24,
        "y": 45
      },
      {
        "kind": "line",
        "points": [
          30,
          30,
          90,
          90
        ]
      }
    ],
    "semanticTone": "ink-muted"
  }
} as const satisfies Record<string, {
  readonly elements: readonly LumenIllustrationElement[]
  readonly semanticTone: LumenIllustrationToneRole
}>


