export const lumenComponentNames = [
  'Accordion',
  'Alert',
  'AlertDialog',
  'Agenda',
  'AspectRatio',
  'Attachment',
  'Autocomplete',
  'Avatar',
  'BackToTop',
  'Badge',
  'BarChart',
  'Breadcrumb',
  'Bubble',
  'Button',
  'ButtonGroup',
  'Calendar',
  'Callout',
  'Card',
  'Carousel',
  'Chart',
  'Checkbox',
  'Collapsible',
  'Code',
  'CodeTabs',
  'Combobox',
  'Command',
  'ContextMenu',
  'ColorPicker',
  'DataTable',
  'DatePicker',
  'DateRangePicker',
  'Dialog',
  'Direction',
  'Drawer',
  'DropdownMenu',
  'Empty',
  'Eyebrow',
  'Field',
  'FloatingBadge',
  'FormattedDate',
  'HoverCard',
  'Icon',
  'Image',
  'Input',
  'InputGroup',
  'InputOTP',
  'Item',
  'Kbd',
  'Label',
  'Link',
  'LineChart',
  'Marker',
  'Menubar',
  'Message',
  'MessageScroller',
  'NativeSelect',
  'NavigationMenu',
  'NumberField',
  'Pagination',
  'PhoneInput',
  'PieChart',
  'Pill',
  'Popover',
  'Progress',
  'Prose',
  'RadioGroup',
  'Resizable',
  'RichTextEditor',
  'ScrollArea',
  'ScrollProgress',
  'Schedule',
  'SearchField',
  'Select',
  'Separator',
  'Sheet',
  'Sidebar',
  'Skeleton',
  'SkipLink',
  'Slider',
  'Sonner',
  'Sparkline',
  'Spinner',
  'Switch',
  'Table',
  'Tabs',
  'TagGroup',
  'Textarea',
  'ThemeBuilder',
  'ThemeToggle',
  'TimeField',
  'Toast',
  'Toggle',
  'ToggleGroup',
  'Tooltip',
  'Tree',
  'TreeGrid',
  'Typography',
  'VirtualList',
  'LanguageToggle',
  'Particles',
  'AnimatedNumber',
  'RevealGroup',
  'ScrollReveal',
  'Stat',
  'Meter',
  'Note',
  'Rating',
  'Timeline',
  'AnimatedLogo',
  'AnimatedPortrait',
  'ButtonLink',
  'CoverImage',
  'GradientDivider',
  'Stepper',
  'FileUpload',
  'Tour',
  'Anchor',
  'Segmented',
  'Toolbar',
  'Descriptions',
  'Popconfirm',
  'Transfer',
  'Cascader',
  'TreeSelect',
  'Mentions',
  'QRCode',
  'Watermark',
  'Affix',
  'SpeedDial'
] as const

export type LumenComponentName = typeof lumenComponentNames[number]

export interface LumenPackageTarget {
  name: string
  packageName: string
  runtime: 'astro' | 'core' | 'elements' | 'icons' | 'react' | 'umbrella'
}

export const lumenPackages = [
  { name: 'Lumen', packageName: '@santi020k/lumen', runtime: 'umbrella' },
  { name: 'Lumen Core', packageName: '@santi020k/lumen-core', runtime: 'core' },
  { name: 'Lumen Astro', packageName: '@santi020k/lumen-astro', runtime: 'astro' },
  { name: 'Lumen React', packageName: '@santi020k/lumen-react', runtime: 'react' },
  { name: 'Lumen Elements', packageName: '@santi020k/lumen-elements', runtime: 'elements' },
  {
    name: 'Lumen Brand Icons',
    packageName: '@santi020k/lumen-icons-brand',
    runtime: 'icons'
  }
] as const satisfies readonly LumenPackageTarget[]
