"""Generate web fonts from the licensed, committed Montserrat variable source.

Run with FontTools 4.60.2 and Brotli 1.2.0 installed in a temporary environment.
"""

# cspell:words fonttools unicodes Cmap Subsetter

from hashlib import sha256
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

root = Path(__file__).resolve().parent.parent
source = root / "public/fonts/Montserrat-Variable.ttf"
latin_ranges = "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
latin_points = subset.parse_unicodes(latin_ranges)
all_points = set(TTFont(source).getBestCmap())
faces = []
latin_url = ""

for name, points in [("latin", set(latin_points) & all_points), ("extended", all_points - set(latin_points))]:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    font = subset.load_font(source, options)
    selection = subset.Subsetter(options)
    selection.populate(unicodes=points)
    selection.subset(font)
    temporary = root / f"public/fonts/Montserrat-{name}.woff2"
    subset.save_font(font, temporary, options)
    digest = sha256(temporary.read_bytes()).hexdigest()[:12]
    filename = f"Montserrat-{name}.{digest}.woff2"
    if name == "latin":
        latin_url = f"/fonts/{filename}"
    temporary.rename(root / "public/fonts" / filename)
    ranges = []
    start = previous = None
    for point in sorted(points):
        if previous is not None and point != previous + 1:
            ranges.append(f"U+{start:X}-{previous:X}" if start != previous else f"U+{start:X}")
            start = None
        if start is None:
            start = point
        previous = point
    ranges.append(f"U+{start:X}-{previous:X}" if start != previous else f"U+{start:X}")
    faces.append(f'''@font-face {{
  font-family: "Montserrat";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("/fonts/{filename}") format("woff2");
  unicode-range: {", ".join(ranges)};
}}''')

(root / "src/styles/fonts.css").write_text("/* Generated by scripts/generate-web-fonts.py. */\n" + "\n\n".join(faces) + "\n")
(root / "src/data/web-font.ts").write_text("// Generated by scripts/generate-web-fonts.py.\n" + f"export const latinFontUrl = '{latin_url}'\n")
