/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenAccessibilityIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Circle cx="16" cy="4" r="1" />
      <Path d="m18 19 1-7-6 1" />
      <Path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <Path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <Path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
  </Svg>
)

export { LumenAccessibilityIconGraphic }
