/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBirdhouseIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 18v4" />
      <Path d="m17 18 1.956-11.468" />
      <Path d="m3 8 7.82-5.615a2 2 0 0 1 2.36 0L21 8" />
      <Path d="M4 18h16" />
      <Path d="M7 18 5.044 6.532" />
      <Circle cx="12" cy="10" r="2" />
  </Svg>
)

export { LumenBirdhouseIconGraphic }
