/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBrandFlipboardIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={color}
    focusable={false}
    height={size}
    stroke={'none'}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={0}
    viewBox="-32 0 512 512"
    width={size}
  >
      <Path d="M0 32l0 448 448 0 0-448-448 0zM358.4 211.2l-89.6 0 0 89.6-89.6 0 0 89.6-89.6 0 0-268.8 268.8 0 0 89.6z" />
  </Svg>
)

export { LumenBrandFlipboardIconGraphic }
