/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBrandBuyselladsIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={color}
    focusable={false}
    height={size}
    stroke={'none'}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={0}
    viewBox="-32 0 512 512"
    width={size}
  >
      <Path d="M224 150.7l42.9 160.7-85.8 0 42.9-160.7zM448 80l0 352c0 26.5-21.5 48-48 48L48 480c-26.5 0-48-21.5-48-48L0 80C0 53.5 21.5 32 48 32l352 0c26.5 0 48 21.5 48 48zM382.7 405.3l-94.5-298.7-128.4 0-94.5 298.7 90.7 0 111.7-91.6 24.2 91.6 90.8 0z" />
  </Svg>
)

export { LumenBrandBuyselladsIconGraphic }
