/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBuildingComplexPlusIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 12h4" />
      <Path d="M10 21v-3a2 2 0 013.05-1.702" />
      <Path d="M10 8h4" />
      <Path d="M16 19h6" />
      <Path d="M18 7h2a2 2 0 012 2v4.355" />
      <Path d="M19 16v6" />
      <Path d="M6 10H4a2 2 0 00-2 2v7a2 2 0 002 2h8.535" />
      <Path d="M6 21V5a2 2 0 012-2h8a2 2 0 012 2v7.126" />
  </Svg>
)

export { LumenBuildingComplexPlusIconGraphic }
