/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBuildingIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 10h.01" />
      <Path d="M12 14h.01" />
      <Path d="M12 6h.01" />
      <Path d="M16 10h.01" />
      <Path d="M16 14h.01" />
      <Path d="M16 6h.01" />
      <Path d="M8 10h.01" />
      <Path d="M8 14h.01" />
      <Path d="M8 6h.01" />
      <Path d="M9 22v-3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3" />
      <Rect x="4" y="2" width="16" height="20" rx="2" />
  </Svg>
)

export { LumenBuildingIconGraphic }
