/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenBusFrontIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M4 6 2 7" />
      <Path d="M10 6h4" />
      <Path d="m22 7-2-1" />
      <Rect width="16" height="16" x="4" y="3" rx="2" />
      <Path d="M4 11h16" />
      <Path d="M8 15h.01" />
      <Path d="M16 15h.01" />
      <Path d="M6 19v2" />
      <Path d="M18 21v-2" />
  </Svg>
)

export { LumenBusFrontIconGraphic }
