/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCableCarIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 3h.01" />
      <Path d="M14 2h.01" />
      <Path d="m2 9 20-5" />
      <Path d="M12 12V6.5" />
      <Rect width="16" height="10" x="4" y="12" rx="3" />
      <Path d="M9 12v5" />
      <Path d="M15 12v5" />
      <Path d="M4 17h16" />
  </Svg>
)

export { LumenCableCarIconGraphic }
