/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCigaretteOffIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 12H3a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h13" />
      <Path d="M18 8c0-2.5-2-2.5-2-5" />
      <Path d="m2 2 20 20" />
      <Path d="M21 12a1 1 0 0 1 1 1v2a1 1 0 0 1-.5.866" />
      <Path d="M22 8c0-2.5-2-2.5-2-5" />
      <Path d="M7 12v4" />
  </Svg>
)

export { LumenCigaretteOffIconGraphic }
