/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCirclePileIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Circle cx="12" cy="19" r="2" />
      <Circle cx="12" cy="5" r="2" />
      <Circle cx="16" cy="12" r="2" />
      <Circle cx="20" cy="19" r="2" />
      <Circle cx="4" cy="19" r="2" />
      <Circle cx="8" cy="12" r="2" />
  </Svg>
)

export { LumenCirclePileIconGraphic }
