/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCircleParkingOffIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12.656 7H13a3 3 0 0 1 2.984 3.307" />
      <Path d="M13 13H9" />
      <Path d="M19.071 19.071A1 1 0 0 1 4.93 4.93" />
      <Path d="m2 2 20 20" />
      <Path d="M8.357 2.687a10 10 0 0 1 12.956 12.956" />
      <Path d="M9 17V9" />
  </Svg>
)

export { LumenCircleParkingOffIconGraphic }
