/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenClockFadingIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 2a10 10 0 0 1 7.38 16.75" />
      <Path d="M12 6v6l4 2" />
      <Path d="M2.5 8.875a10 10 0 0 0-.5 3" />
      <Path d="M2.83 16a10 10 0 0 0 2.43 3.4" />
      <Path d="M4.636 5.235a10 10 0 0 1 .891-.857" />
      <Path d="M8.644 21.42a10 10 0 0 0 7.631-.38" />
  </Svg>
)

export { LumenClockFadingIconGraphic }
