/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCogIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11 10.27 7 3.34" />
      <Path d="m11 13.73-4 6.93" />
      <Path d="M12 22v-2" />
      <Path d="M12 2v2" />
      <Path d="M14 12h8" />
      <Path d="m17 20.66-1-1.73" />
      <Path d="m17 3.34-1 1.73" />
      <Path d="M2 12h2" />
      <Path d="m20.66 17-1.73-1" />
      <Path d="m20.66 7-1.73 1" />
      <Path d="m3.34 17 1.73-1" />
      <Path d="m3.34 7 1.73 1" />
      <Circle cx="12" cy="12" r="2" />
      <Circle cx="12" cy="12" r="8" />
  </Svg>
)

export { LumenCogIconGraphic }
