/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCombineIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M14 3a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1" />
      <Path d="M19 3a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1" />
      <Path d="m7 15 3 3" />
      <Path d="m7 21 3-3H5a2 2 0 0 1-2-2v-2" />
      <Rect x="14" y="14" width="7" height="7" rx="1" />
      <Rect x="3" y="3" width="7" height="7" rx="1" />
  </Svg>
)

export { LumenCombineIconGraphic }
