/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Line, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenCrosshairIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Circle cx="12" cy="12" r="10" />
      <Line x1="22" x2="18" y1="12" y2="12" />
      <Line x1="6" x2="2" y1="12" y2="12" />
      <Line x1="12" x2="12" y1="6" y2="2" />
      <Line x1="12" x2="12" y1="22" y2="18" />
  </Svg>
)

export { LumenCrosshairIconGraphic }
