/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Ellipse, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenDatabaseMinusIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M21 15V5" />
      <Path d="M22 19h-6" />
      <Path d="M3 12A9 3 0 0 0 21 12" />
      <Path d="M3 5V19A9 3 0 0 0 13.318 21.968" />
      <Ellipse cx="12" cy="5" rx="9" ry="3" />
  </Svg>
)

export { LumenDatabaseMinusIconGraphic }
