/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenDecimalsArrowRightIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 18h10" />
      <Path d="m17 21 3-3-3-3" />
      <Path d="M3 11h.01" />
      <Rect x="15" y="3" width="5" height="8" rx="2.5" />
      <Rect x="6" y="3" width="5" height="8" rx="2.5" />
  </Svg>
)

export { LumenDecimalsArrowRightIconGraphic }
