/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenFaceAngryIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M15 12v-1.584" />
      <Path d="M17 10a5 5 0 00-3 1" />
      <Path d="M7 10a5 5 0 013 1" />
      <Path d="M9 12v-1.584" />
      <Path d="M9 17a5 5 0 016.001 0" />
      <Circle cx="12" cy="12" r="10" />
  </Svg>
)

export { LumenFaceAngryIconGraphic }
