/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenFlowerIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Circle cx="12" cy="12" r="3" />
      <Path d="M12 16.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 1 1 12 7.5a4.5 4.5 0 1 1 4.5 4.5 4.5 4.5 0 1 1-4.5 4.5" />
      <Path d="M12 7.5V9" />
      <Path d="M7.5 12H9" />
      <Path d="M16.5 12H15" />
      <Path d="M12 16.5V15" />
      <Path d="m8 8 1.88 1.88" />
      <Path d="M14.12 9.88 16 8" />
      <Path d="m8 16 1.88-1.88" />
      <Path d="M14.12 14.12 16 16" />
  </Svg>
)

export { LumenFlowerIconGraphic }
