/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenHazeIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="m5.2 6.2 1.4 1.4" />
      <Path d="M2 13h2" />
      <Path d="M20 13h2" />
      <Path d="m17.4 7.6 1.4-1.4" />
      <Path d="M22 17H2" />
      <Path d="M22 21H2" />
      <Path d="M16 13a4 4 0 0 0-8 0" />
      <Path d="M12 5V2.5" />
  </Svg>
)

export { LumenHazeIconGraphic }
