/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenHeaterIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11 8c2-3-2-3 0-6" />
      <Path d="M15.5 8c2-3-2-3 0-6" />
      <Path d="M6 10h.01" />
      <Path d="M6 14h.01" />
      <Path d="M10 16v-4" />
      <Path d="M14 16v-4" />
      <Path d="M18 16v-4" />
      <Path d="M20 6a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h3" />
      <Path d="M5 20v2" />
      <Path d="M19 20v2" />
  </Svg>
)

export { LumenHeaterIconGraphic }
