/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenHouseCogIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10.584 21H5a2 2 0 01-2-2v-9a2 2 0 01.709-1.527l7-6a2 2 0 012.582 0l7 6A2 2 0 0121 10.001v.583" />
      <Path d="M14 12H10a1 1 0 00-1 1v8" />
      <Path d="m14.305 19.53.923-.382" />
      <Path d="m15.229 16.852-.924-.383" />
      <Path d="m16.852 15.228-.383-.923" />
      <Path d="m16.852 20.773-.383.924" />
      <Path d="m19.148 15.228.383-.923" />
      <Path d="m19.53 21.697-.382-.924" />
      <Path d="m20.773 16.852.922-.383" />
      <Path d="m20.773 19.148.922.383" />
      <Circle cx="18" cy="18" r="3" />
  </Svg>
)

export { LumenHouseCogIconGraphic }
