/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenKeyboardMusicIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Rect width="20" height="16" x="2" y="4" rx="2" />
      <Path d="M6 8h4" />
      <Path d="M14 8h.01" />
      <Path d="M18 8h.01" />
      <Path d="M2 12h20" />
      <Path d="M6 12v4" />
      <Path d="M10 12v4" />
      <Path d="M14 12v4" />
      <Path d="M18 12v4" />
  </Svg>
)

export { LumenKeyboardMusicIconGraphic }
