/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenMemoryStickIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 12v-2" />
      <Path d="M12 18v-2" />
      <Path d="M16 12v-2" />
      <Path d="M16 18v-2" />
      <Path d="M2 11h1.5" />
      <Path d="M20 18v-2" />
      <Path d="M20.5 11H22" />
      <Path d="M4 18v-2" />
      <Path d="M8 12v-2" />
      <Path d="M8 18v-2" />
      <Rect x="2" y="6" width="20" height="10" rx="2" />
  </Svg>
)

export { LumenMemoryStickIconGraphic }
