/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenMessagesSquareIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
      <Path d="M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1" />
  </Svg>
)

export { LumenMessagesSquareIconGraphic }
