/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenMessageSquareDashedIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M14 3h2" />
      <Path d="M16 19h-2" />
      <Path d="M2 12v-2" />
      <Path d="M2 16v5.286a.71.71 0 0 0 1.212.502l1.149-1.149" />
      <Path d="M20 19a2 2 0 0 0 2-2v-1" />
      <Path d="M22 10v2" />
      <Path d="M22 6V5a2 2 0 0 0-2-2" />
      <Path d="M4 3a2 2 0 0 0-2 2v1" />
      <Path d="M8 19h2" />
      <Path d="M8 3h2" />
  </Svg>
)

export { LumenMessageSquareDashedIconGraphic }
