/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenMessageCircleDashedIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10.1 2.182a10 10 0 0 1 3.8 0" />
      <Path d="M13.9 21.818a10 10 0 0 1-3.8 0" />
      <Path d="M17.609 3.72a10 10 0 0 1 2.69 2.7" />
      <Path d="M2.182 13.9a10 10 0 0 1 0-3.8" />
      <Path d="M20.28 17.61a10 10 0 0 1-2.7 2.69" />
      <Path d="M21.818 10.1a10 10 0 0 1 0 3.8" />
      <Path d="M3.721 6.391a10 10 0 0 1 2.7-2.69" />
      <Path d="m6.163 21.117-2.906.85a1 1 0 0 1-1.236-1.169l.965-2.98" />
  </Svg>
)

export { LumenMessageCircleDashedIconGraphic }
