/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenMicAudioLinesIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 3v2.341" />
      <Path d="M12 17v4" />
      <Path d="M14 5v.341" />
      <Path d="M18 5v13" />
      <Path d="M2 10v3" />
      <Path d="M22 10v3" />
      <Path d="M6 6v11" />
      <Path d="M9 21h6" />
      <Rect width="4" height="8" x="10" y="9" rx="2" />
  </Svg>
)

export { LumenMicAudioLinesIconGraphic }
