/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenNfcIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M6 8.32a7.43 7.43 0 0 1 0 7.36" />
      <Path d="M9.46 6.21a11.76 11.76 0 0 1 0 11.58" />
      <Path d="M12.91 4.1a15.91 15.91 0 0 1 .01 15.8" />
      <Path d="M16.37 2a20.16 20.16 0 0 1 0 20" />
  </Svg>
)

export { LumenNfcIconGraphic }
