/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenOrbitIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M20.341 6.484A10 10 0 0 1 10.266 21.85" />
      <Path d="M3.659 17.516A10 10 0 0 1 13.74 2.152" />
      <Circle cx="12" cy="12" r="3" />
      <Circle cx="19" cy="5" r="2" />
      <Circle cx="5" cy="19" r="2" />
  </Svg>
)

export { LumenOrbitIconGraphic }
