/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenPackageXIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 22V12" />
      <Path d="m16.5 14.5 5 5" />
      <Path d="m16.5 19.5 5-5" />
      <Path d="M21 10.5V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.729l7 4a2 2 0 0 0 2 .001l.13-.074" />
      <Path d="M3.29 7 12 12l8.71-5" />
      <Path d="m7.5 4.27 8.997 5.148" />
  </Svg>
)

export { LumenPackageXIconGraphic }
