/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenPanelTopBottomDashedIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M14 15h1" />
      <Path d="M14 9h1" />
      <Path d="M19 15h2" />
      <Path d="M19 9h2" />
      <Path d="M3 15h2" />
      <Path d="M3 9h2" />
      <Path d="M9 15h1" />
      <Path d="M9 9h1" />
      <Rect x="3" y="3" width="18" height="18" rx="2" />
  </Svg>
)

export { LumenPanelTopBottomDashedIconGraphic }
