/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenPictureInPictureIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M2 10h6V4" />
      <Path d="m2 4 6 6" />
      <Path d="M21 10V7a2 2 0 0 0-2-2h-7" />
      <Path d="M3 14v2a2 2 0 0 0 2 2h3" />
      <Rect x="12" y="14" width="10" height="7" rx="1" />
  </Svg>
)

export { LumenPictureInPictureIconGraphic }
