/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRadioTowerIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M4.9 16.1C1 12.2 1 5.8 4.9 1.9" />
      <Path d="M7.8 4.7a6.14 6.14 0 0 0-.8 7.5" />
      <Circle cx="12" cy="9" r="2" />
      <Path d="M16.2 4.8c2 2 2.26 5.11.8 7.47" />
      <Path d="M19.1 1.9a9.96 9.96 0 0 1 0 14.1" />
      <Path d="M9.5 18h5" />
      <Path d="m8 22 4-11 4 11" />
  </Svg>
)

export { LumenRadioTowerIconGraphic }
