/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRadioIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M16.247 7.761a6 6 0 0 1 0 8.478" />
      <Path d="M19.075 4.933a10 10 0 0 1 0 14.134" />
      <Path d="M4.925 19.067a10 10 0 0 1 0-14.134" />
      <Path d="M7.753 16.239a6 6 0 0 1 0-8.478" />
      <Circle cx="12" cy="12" r="2" />
  </Svg>
)

export { LumenRadioIconGraphic }
