/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRepeatOffIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11.656 6H21l-4-4" />
      <Path d="M17.898 17.898A4 4 0 0 1 17 18H3l4-4" />
      <Path d="m2 2 20 20" />
      <Path d="M21 13v1a4 4 0 0 1-.171 1.159" />
      <Path d="m21 6-4 4" />
      <Path d="M3 11v-1a4 4 0 0 1 3.102-3.898" />
      <Path d="m7 22-4-4" />
  </Svg>
)

export { LumenRepeatOffIconGraphic }
