/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRobotVacuumIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11 17h2" />
      <Path d="M12 12h.01" />
      <Path d="M17 12a5 5 0 00-10 0" />
      <Path d="M19 2v2.8" />
      <Path d="M2 5h2.8" />
      <Path d="M22 5h-2.8" />
      <Path d="M5 2v2.8" />
      <Circle cx="12" cy="12" r="10" />
  </Svg>
)

export { LumenRobotVacuumIconGraphic }
