/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRobotArmIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 21 7.5 8.322" />
      <Path d="m14 7 1.75-3.767a.5.5 0 0 1 .662-.172L20 5.005" />
      <Path d="m20 8.998-3.588 1.944a.5.5 0 0 1-.662-.172L14 7H8" />
      <Path d="M3.486 21h10" />
      <Path d="M5 21V8.732" />
      <Circle cx="6" cy="7" r="2" />
  </Svg>
)

export { LumenRobotArmIconGraphic }
