/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenRouterIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Rect width="20" height="8" x="2" y="14" rx="2" />
      <Path d="M6.01 18H6" />
      <Path d="M10.01 18H10" />
      <Path d="M15 10v4" />
      <Path d="M17.84 7.17a4 4 0 0 0-5.66 0" />
      <Path d="M20.66 4.34a8 8 0 0 0-11.31 0" />
  </Svg>
)

export { LumenRouterIconGraphic }
