/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenScissorsLineDashedIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M5.42 9.42 8 12" />
      <Circle cx="4" cy="8" r="2" />
      <Path d="m14 6-8.58 8.58" />
      <Circle cx="4" cy="16" r="2" />
      <Path d="M10.8 14.8 14 18" />
      <Path d="M16 12h-2" />
      <Path d="M22 12h-2" />
  </Svg>
)

export { LumenScissorsLineDashedIconGraphic }
