/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Rect, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenSendToBackIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Rect x="14" y="14" width="8" height="8" rx="2" />
      <Rect x="2" y="2" width="8" height="8" rx="2" />
      <Path d="M7 14v1a2 2 0 0 0 2 2h1" />
      <Path d="M14 7h1a2 2 0 0 1 2 2v1" />
  </Svg>
)

export { LumenSendToBackIconGraphic }
