/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenShieldCogIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="m10.929 14.467-.383.924" />
      <Path d="M10.929 8.923 10.546 8" />
      <Path d="M13.225 8.923 13.608 8" />
      <Path d="m13.607 15.391-.382-.924" />
      <Path d="m14.849 10.547.923-.383" />
      <Path d="m14.849 12.843.923.383" />
      <Path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
      <Path d="m9.305 10.547-.923-.383" />
      <Path d="m9.305 12.843-.923.383" />
      <Circle cx="12.077" cy="11.695" r="3" />
  </Svg>
)

export { LumenShieldCogIconGraphic }
