/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenShrinkIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="m15 15 6 6m-6-6v4.8m0-4.8h4.8" />
      <Path d="M9 19.8V15m0 0H4.2M9 15l-6 6" />
      <Path d="M15 4.2V9m0 0h4.8M15 9l6-6" />
      <Path d="M9 4.2V9m0 0H4.2M9 9 3 3" />
  </Svg>
)

export { LumenShrinkIconGraphic }
