/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenSquaresIntersectIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 22a2 2 0 0 1-2-2" />
      <Path d="M14 2a2 2 0 0 1 2 2" />
      <Path d="M16 22h-2" />
      <Path d="M2 10V8" />
      <Path d="M2 4a2 2 0 0 1 2-2" />
      <Path d="M20 8a2 2 0 0 1 2 2" />
      <Path d="M22 14v2" />
      <Path d="M22 20a2 2 0 0 1-2 2" />
      <Path d="M4 16a2 2 0 0 1-2-2" />
      <Path d="M8 10a2 2 0 0 1 2-2h5a1 1 0 0 1 1 1v5a2 2 0 0 1-2 2H9a1 1 0 0 1-1-1z" />
      <Path d="M8 2h2" />
  </Svg>
)

export { LumenSquaresIntersectIconGraphic }
