/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenSquareDashedXCornerIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M14 3h1" />
      <Path d="m16 16 5 5" />
      <Path d="M19 3a2 2 0 012 2" />
      <Path d="m21 16-5 5" />
      <Path d="M21 9v1" />
      <Path d="M3 14v1" />
      <Path d="M3 9v1" />
      <Path d="M5 21a2 2 0 01-2-2" />
      <Path d="M5 3a2 2 0 00-2 2" />
      <Path d="M9 21h1" />
      <Path d="M9 3h1" />
  </Svg>
)

export { LumenSquareDashedXCornerIconGraphic }
