/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenSquareDashedTextIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M14 21h1" />
      <Path d="M14 3h1" />
      <Path d="M19 3a2 2 0 0 1 2 2" />
      <Path d="M21 14v1" />
      <Path d="M21 19a2 2 0 0 1-2 2" />
      <Path d="M21 9v1" />
      <Path d="M3 14v1" />
      <Path d="M3 9v1" />
      <Path d="M5 21a2 2 0 0 1-2-2" />
      <Path d="M5 3a2 2 0 0 0-2 2" />
      <Path d="M7 12h10" />
      <Path d="M7 16h6" />
      <Path d="M7 8h8" />
      <Path d="M9 21h1" />
      <Path d="M9 3h1" />
  </Svg>
)

export { LumenSquareDashedTextIconGraphic }
