/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenSunSnowIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 21v-1" />
      <Path d="M10 4V3" />
      <Path d="M10 9a3 3 0 0 0 0 6" />
      <Path d="m14 20 1.25-2.5L18 18" />
      <Path d="m14 4 1.25 2.5L18 6" />
      <Path d="m17 21-3-6 1.5-3H22" />
      <Path d="m17 3-3 6 1.5 3" />
      <Path d="M2 12h1" />
      <Path d="m20 10-1.5 2 1.5 2" />
      <Path d="m3.64 18.36.7-.7" />
      <Path d="m4.34 6.34-.7-.7" />
  </Svg>
)

export { LumenSunSnowIconGraphic }
