/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenThermometerSnowflakeIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="m10 20-1.25-2.5L6 18" />
      <Path d="M10 4 8.75 6.5 6 6" />
      <Path d="M10.585 15H10" />
      <Path d="M2 12h6.5L10 9" />
      <Path d="M20 14.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z" />
      <Path d="m4 10 1.5 2L4 14" />
      <Path d="m7 21 3-6-1.5-3" />
      <Path d="m7 3 3 6h2" />
  </Svg>
)

export { LumenThermometerSnowflakeIconGraphic }
