/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenThermometerSunIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 2v2" />
      <Path d="M12 8a4 4 0 0 0-1.645 7.647" />
      <Path d="M2 12h2" />
      <Path d="M20 14.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0z" />
      <Path d="m4.93 4.93 1.41 1.41" />
      <Path d="m6.34 17.66-1.41 1.41" />
  </Svg>
)

export { LumenThermometerSunIconGraphic }
