/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenTrashOffIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10 11v6" />
      <Path d="M14 17v-3" />
      <Path d="M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-1.576.768" />
      <Path d="M19 6v7.344" />
      <Path d="m2 2 20 20" />
      <Path d="M21 6h-9.344" />
      <Path d="M3 6h3" />
      <Path d="M5 6v14a2 2 0 002 2h10a2 2 0 002-2v-1" />
  </Svg>
)

export { LumenTrashOffIconGraphic }
