/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenTriangleDashedIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M10.17 4.193a2 2 0 0 1 3.666.013" />
      <Path d="M14 21h2" />
      <Path d="m15.874 7.743 1 1.732" />
      <Path d="m18.849 12.952 1 1.732" />
      <Path d="M21.824 18.18a2 2 0 0 1-1.835 2.824" />
      <Path d="M4.024 21a2 2 0 0 1-1.839-2.839" />
      <Path d="m5.136 12.952-1 1.732" />
      <Path d="M8 21h2" />
      <Path d="m8.102 7.743-1 1.732" />
  </Svg>
)

export { LumenTriangleDashedIconGraphic }
