/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenUnfoldHorizontalIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M16 12h6" />
      <Path d="M8 12H2" />
      <Path d="M12 2v2" />
      <Path d="M12 8v2" />
      <Path d="M12 14v2" />
      <Path d="M12 20v2" />
      <Path d="m19 15 3-3-3-3" />
      <Path d="m5 9-3 3 3 3" />
  </Svg>
)

export { LumenUnfoldHorizontalIconGraphic }
