/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenUsbIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Circle cx="10" cy="7" r="1" />
      <Circle cx="4" cy="20" r="1" />
      <Path d="M4.7 19.3 19 5" />
      <Path d="m21 3-3 1 2 2Z" />
      <Path d="M9.26 7.68 5 12l2 5" />
      <Path d="m10 14 5 2 3.5-3.5" />
      <Path d="m18 12 1-1 1 1-1 1Z" />
  </Svg>
)

export { LumenUsbIconGraphic }
