/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenUserGroupIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M17 21v-1a2 2 0 00-2-2H9a2 2 0 00-2 2v1" />
      <Path d="M19 10h1a2 2 0 012 2v1" />
      <Path d="M5 10H4a2 2 0 00-2 2v1" />
      <Circle cx="12" cy="11" r="3" />
      <Circle cx="18" cy="4" r="2" />
      <Circle cx="6" cy="4" r="2" />
  </Svg>
)

export { LumenUserGroupIconGraphic }
