/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenVirusIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M12 14.991h.01" />
      <Path d="M12 22v-3" />
      <Path d="M12 2v3" />
      <Path d="M13 22h-2" />
      <Path d="M13 2h-2" />
      <Path d="M13.99 10H14" />
      <Path d="m16.5 19.794-1-1.733" />
      <Path d="m16.5 4.205-1 1.732" />
      <Path d="m19.794 16.5-1.732-1" />
      <Path d="m19.794 7.5-1.732 1" />
      <Path d="M2 12h3" />
      <Path d="M2 13v-2" />
      <Path d="M22 12h-3" />
      <Path d="M22 13v-2" />
      <Path d="m4.206 16.5 1.732-1" />
      <Path d="m4.206 7.5 1.732 1" />
      <Path d="m7.5 19.794 1-1.733" />
      <Path d="m7.5 4.205 1 1.732" />
      <Path d="M9 12h.01" />
      <Circle cx="12" cy="12" r="7" />
  </Svg>
)

export { LumenVirusIconGraphic }
