/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenVolleyballIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11 7a16 16 20 0 1 10.98 4.362" />
      <Path d="M12 12a13 13 0 0 1-8.66 5" />
      <Path d="M16.83 13.634a16 16 0 0 1-9.267 7.328" />
      <Path d="M20.66 17A13 13 0 0 0 12 12a13 13 0 0 1 0-10" />
      <Path d="M8.17 15.366a16 16 0 0 1-1.713-11.69" />
      <Circle cx="12" cy="12" r="10" />
  </Svg>
)

export { LumenVolleyballIconGraphic }
