/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Circle, Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenWaypointsIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="m10.586 5.414-5.172 5.172" />
      <Path d="m18.586 13.414-5.172 5.172" />
      <Path d="M6 12h12" />
      <Circle cx="12" cy="20" r="2" />
      <Circle cx="12" cy="4" r="2" />
      <Circle cx="20" cy="12" r="2" />
      <Circle cx="4" cy="12" r="2" />
  </Svg>
)

export { LumenWaypointsIconGraphic }
