/* This file is generated by scripts/generate-platform-icons.mjs.
 * Lucide artwork: ISC; Font Awesome brand artwork: CC BY 4.0.
 * See THIRD_PARTY_NOTICES.md for attribution and license terms.
 */

import type { ReactElement } from 'react'
import { Path, Svg } from 'react-native-svg'

import type { LumenIconGraphicProps } from '../icon-primitives.js'

const LumenZodiacVirgoIconGraphic = ({
  color = 'currentColor',
  size = 24,
  strokeWidth = 2
}: LumenIconGraphicProps): ReactElement => (
  <Svg
    fill={'none'}
    focusable={false}
    height={size}
    stroke={color}
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth={strokeWidth}
    viewBox="0 0 24 24"
    width={size}
  >
      <Path d="M11 5.5a1 1 0 0 1 5 0V16a5 5 0 0 0 5 5" />
      <Path d="M16 11.5a1 1 0 0 1 5 0V16a5 5 0 0 1-5 5" />
      <Path d="M6 19V6a3 3 0 0 0-3-3h0" />
      <Path d="M6 5.5a1 1 0 0 1 5 0V19" />
  </Svg>
)

export { LumenZodiacVirgoIconGraphic }
