const reservedNames = new Set([
  'arguments',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'eval',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield'
])

// Names are interpolated into identifiers and custom-element tag names in the
// generated wrappers. Use their shared ASCII subset, without module keywords.
export const isSafeRegistryComponentName = (name: unknown): name is string => (
  typeof name === 'string' && /^[A-Za-z_][A-Za-z0-9_]*(?![\s\S])/u.test(name) && !reservedNames.has(name)
)
