// This file is generated by scripts/generate-native-playground-catalogs.mjs.

package com.santi020k.lumen.playground.compose

internal data class PlaygroundSection(
    val description: String,
    val names: Set<String>,
    val title: String
)

internal const val playgroundLumenVersion = "4.0.0"

internal val playgroundSections = listOf(
    PlaygroundSection(
        title = "Foundations",
        description = "Theme, type, surfaces, icons, and visual treatments.",
        names = setOf(
            "Theme",
            "Text",
            "Surface",
            "Icon",
            "Icon button",
            "Graphic",
            "Backdrop",
            "Illustration",
            "Image"
        )
    ),
    PlaygroundSection(
        title = "Actions",
        description = "Buttons, chips, menus, and operating-system actions.",
        names = setOf(
            "Button",
            "Button group",
            "Chip",
            "Menu",
            "Share button",
            "Floating action button",
            "Tooltip",
            "Swipe actions"
        )
    ),
    PlaygroundSection(
        title = "Forms",
        description = "Editable values, choices, validation, and date input.",
        names = setOf(
            "Text field",
            "Textarea",
            "Field group",
            "Toggle",
            "Settings row",
            "Search field",
            "Date field",
            "Date range field",
            "Phone input",
            "Checkbox",
            "Radio group",
            "Segmented control",
            "Tabs",
            "Picker",
            "Slider",
            "Range slider",
            "Time field",
            "Autocomplete",
            "Number field",
            "Password field",
            "Input OTP",
            "Multi select",
            "Rating",
            "Cascader",
            "Color picker",
            "Tree select",
            "Transfer"
        )
    ),
    PlaygroundSection(
        title = "Feedback",
        description = "Progress, alerts, loading, recovery, and transient status.",
        names = setOf(
            "Badge",
            "Divider",
            "Spinner",
            "Alert",
            "Toast",
            "Progress",
            "Skeleton",
            "Empty state",
            "Error state",
            "Banner",
            "Stepper",
            "Timeline",
            "Pull to refresh"
        )
    ),
    PlaygroundSection(
        title = "Data",
        description = "Cards, charts, rows, metrics, disclosure, and identity.",
        names = setOf(
            "Card",
            "Sparkline",
            "Line chart",
            "Bar chart",
            "Pie chart",
            "Scatter chart",
            "Waterfall chart",
            "Histogram",
            "Heatmap",
            "Range chart",
            "Combo chart",
            "Disclosure",
            "Avatar",
            "List row",
            "Stat",
            "Section header",
            "Status bar",
            "Gauge",
            "Image comparison",
            "Bullet chart",
            "Lollipop chart",
            "Dumbbell chart",
            "Calendar heatmap",
            "Funnel chart",
            "Box plot",
            "Table",
            "Data table",
            "Tree",
            "QR code",
            "Calendar",
            "Agenda",
            "Kanban board",
            "Kanban column",
            "Schedule"
        )
    ),
    PlaygroundSection(
        title = "Navigation",
        description = "Dialogs, sheets, destination bars, and accessories.",
        names = setOf(
            "Alert dialog",
            "Sheet",
            "Navigation bar",
            "Breadcrumb",
            "Navigation bar scroll behavior",
            "Navigation bar accessory",
            "Adaptive navigation scaffold",
            "Top app bar",
            "Adaptive list detail scaffold"
        )
    )
)
