'use client'

import {
  createElement,
  type HTMLAttributes,
  type ReactNode,
  useEffect,
  useState } from 'react'

interface LumenElementProps extends HTMLAttributes<HTMLElement> {
  as: `lumen-${string}`
  max?: string
  min?: string
  month?: string
  name?: string
  value?: string
}

const LumenElement = ({ as, children, ...props }: LumenElementProps) => (
  createElement(as, props, children)
)

const StatElement = ({ children }: { children: ReactNode }) => (
  <LumenElement as="lumen-stat">{children}</LumenElement>
)

export const ElementsVisualHost = () => {
  const [progress, setProgress] = useState(72)
  const [ready, setReady] = useState(false)

  useEffect(() => {
    let mounted = true

    const register = async () => {
      const { defineLumenElements } = await import('@santi020k/lumen-elements/define')

      defineLumenElements()

      if (mounted) setReady(true)
    }

    void register()

    return () => {
      mounted = false
    }
  }, [])

  return (
    <main className="visual-host" data-framework="elements">
      <header className="visual-host__hero">
        <div>
          <LumenElement as="lumen-badge" className="ui-badge--secondary">
            Custom Elements runtime
          </LumenElement>
          <h1>Real Web Component rendering</h1>
          <p>Registered lumen-* elements with live attributes and behavior controllers.</p>
        </div>
        <LumenElement
          aria-label="Advance Web Component release"
          as="lumen-button"
          data-ready={String(ready)}
          onClick={() => {
            setProgress(value => value >= 100 ? 28 : value + 7)
          }}
        >
          Advance release
        </LumenElement>
      </header>

      <section className="visual-host__stats" aria-label="Web Component status">
        <StatElement>
          <span className="ui-stat-label">Definitions</span>
          <strong className="ui-stat-value">156</strong>
          <span className="ui-stat-description">Constructor exports</span>
        </StatElement>
        <StatElement>
          <span className="ui-stat-label">Coverage</span>
          <strong className="ui-stat-value">
            {progress}
            %
          </strong>
          <span className="ui-stat-trend ui-stat-trend--success">+7 this run</span>
        </StatElement>
        <StatElement>
          <span className="ui-stat-label">Registry</span>
          <strong className="ui-stat-value">{ready ? 'Ready' : 'Loading'}</strong>
          <span className="ui-stat-description">customElements</span>
        </StatElement>
      </section>

      <section className="visual-host__grid">
        <LumenElement as="lumen-card">
          <div className="ui-card-header">
            <h2 className="ui-card-title">Release readiness</h2>
            <p className="ui-card-description">Attributes update the registered element.</p>
          </div>
          <div className="ui-card-content visual-host__stack">
            <LumenElement
              aria-label="Web Component release readiness"
              as="lumen-progress"
              max="100"
              value={String(progress)}
            />
            <LumenElement as="lumen-alert">
              {progress >= 93 ? 'Ready for final review.' : 'Verification is still running.'}
            </LumenElement>
          </div>
        </LumenElement>

        <LumenElement as="lumen-card">
          <div className="ui-card-header">
            <h2 className="ui-card-title">Delivery window</h2>
            <p className="ui-card-description">Generated by the calendar controller.</p>
          </div>
          <div className="ui-card-content">
            <LumenElement
              as="lumen-calendar"
              max="2026-09-30"
              min="2026-07-01"
              month="2026-08"
              name="releaseDate"
              value="2026-08-25"
            />
          </div>
        </LumenElement>
      </section>

      <LumenElement as="lumen-tabs">
        <div aria-label="Elements visual evidence" role="tablist">
          <button
            aria-controls="elements-packages"
            aria-selected="true"
            id="elements-packages-tab"
            role="tab"
            type="button"
          >
            Packages
          </button>
          <button
            aria-controls="elements-notes"
            aria-selected="false"
            id="elements-notes-tab"
            role="tab"
            type="button"
          >
            Notes
          </button>
        </div>
        <section aria-labelledby="elements-packages-tab" id="elements-packages" role="tabpanel">
          <LumenElement as="lumen-data-table">
            <table>
              <thead>
                <tr>
                  <th data-sortable="">Package</th>
                  <th data-sortable="">Platform</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>lumen-elements</td>
                  <td>Web</td>
                  <td>Ready</td>
                </tr>
                <tr>
                  <td>LumenUI</td>
                  <td>Apple</td>
                  <td>Ready</td>
                </tr>
                <tr>
                  <td>lumen-compose</td>
                  <td>Android</td>
                  <td>Review</td>
                </tr>
              </tbody>
            </table>
          </LumenElement>
        </section>
        <section aria-labelledby="elements-notes-tab" hidden id="elements-notes" role="tabpanel">
          <p className="visual-host__note">
            Tabs, calendar generation, progress attributes, and table sorting are owned by the
            registered Web Component adapter.
          </p>
        </section>
      </LumenElement>
    </main>
  )
}
