import { createRequire } from 'node:module'

import { expect, test } from '@playwright/test'

const axePath = createRequire(new URL('../../packages/elements/package.json', import.meta.url)).resolve('axe-core/axe.min.js')

for (const width of [390, 1440]) {
  test(`operational views, selection and reviewed changes at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/docs/web/consumer-workflows')
    const table = page.getByRole('region', { name: 'Operational example records', exact: true }).getByRole('table')
    await expect(table).toContainText('Example record C')
    await page.getByLabel('Saved view', { exact: true }).selectOption('due')
    await expect(table).not.toContainText('Example record C')
    await page.getByLabel('Amount COP: from', { exact: true }).fill('200000')
    await expect(table).not.toContainText('Example record A')
    await expect(table).toContainText('Example record B')
    await page.getByLabel('New view name', { exact: true }).fill('Larger due records')
    await page.getByRole('button', { name: 'Save new view', exact: true }).click()
    await page.getByRole('button', { name: 'Reset view', exact: true }).click()
    await expect(table).toContainText('Example record A')
    await page.getByLabel('Saved view', { exact: true }).selectOption({ label: 'Larger due records' })
    await expect(table).not.toContainText('Example record A')
    await page.getByLabel('Select eligible records on this page', { exact: true }).check()
    await page.getByRole('button', { name: 'Preview selected export', exact: true }).click()
    await expect(page.getByLabel('Selected export preview', { exact: true })).toHaveText('example-2')
    await page.getByRole('button', { name: 'Reset view', exact: true }).click()
    await expect(page.getByLabel('Select Example record C', { exact: true })).toBeDisabled()
    await expect(page.getByLabel('Select Example record B', { exact: true })).toBeChecked()
    await expect(page.getByLabel('Select eligible records on this page', { exact: true })).toHaveJSProperty('indeterminate', true)
    await page.getByRole('button', { name: 'Clear selection', exact: true }).click()
    await expect(page.getByLabel('Select Example record B', { exact: true })).not.toBeChecked()
    await page.getByLabel('Due date: from', { exact: true }).fill('2026-10-10')
    await expect(table).not.toContainText('Example record A')
    await expect(table).toContainText('Example record B')
    await page.getByRole('button', { name: 'Reset view', exact: true }).click()

    const form = page.getByRole('form', { name: 'Reviewed example change', exact: true })
    const amount = form.getByRole('textbox', { name: 'Reviewed amount COP', exact: true })
    await amount.fill('125.000')
    await form.getByLabel('Reviewed due date', { exact: true }).fill('2026-10-12')
    await form.getByRole('button', { name: 'Review proposed change', exact: true }).click()
    await expect(form.getByRole('region', { name: 'Review proposed change', exact: true })).toBeFocused()
    await expect(form).toContainText('125000')
    await amount.fill('150.000')
    await expect(form.getByRole('button', { name: 'Confirm reviewed change', exact: true })).toHaveCount(0)
    await form.getByRole('button', { name: 'Review proposed change', exact: true }).click()
    await form.getByRole('button', { name: 'Confirm reviewed change', exact: true }).click()
    await expect(page.getByLabel('Confirmed example value', { exact: true })).toHaveText('150000 COP · 2026-10-12')

    const review = page.getByRole('region', { name: 'Synthetic import review', exact: true })
    await expect(review.getByRole('button', { name: 'Confirm example import', exact: true })).toBeDisabled()
    await review.getByRole('button', { name: 'Next proposal', exact: true }).click()
    await expect(review.getByRole('region', { name: 'Example record B', exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Resolve example finding', exact: true }).click()
    await review.getByRole('button', { name: 'Confirm example import', exact: true }).click()
    await expect(page.getByText('Example import confirmed. No data was persisted.', { exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Example record workspace', exact: true })).toContainText('Original event: EXAMPLE-EVENT-001')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

    await page.addScriptTag({ path: axePath })
    const violations: unknown = await page.evaluate('axe.run(".consumer-workflows", { runOnly: { type: "tag", values: ["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"] } }).then(result => result.violations)')
    expect(violations).toEqual([])
    await page.screenshot({ path: testInfo.outputPath(`operational-workflows-after-${width}.png`), fullPage: true })
    await form.screenshot({ path: testInfo.outputPath(`review-workflow-${width}.png`) })
  })
}

test('failed and uncertain commands retain exact inputs and require explicit recovery', async ({ page }) => {
  await page.goto('/docs/web/consumer-workflows')
  const form = page.getByRole('form', { name: 'Reviewed example change', exact: true })
  const amount = form.getByRole('textbox', { name: 'Reviewed amount COP', exact: true })
  await page.getByLabel('Simulated save result', { exact: true }).selectOption('failure')
  await amount.fill('200.000')
  await form.getByRole('button', { name: 'Review proposed change', exact: true }).click()
  await form.getByRole('button', { name: 'Confirm reviewed change', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('Your input is retained.')
  await expect(amount).toHaveValue('200.000')
  await page.getByLabel('Simulated save result', { exact: true }).selectOption('uncertain')
  await form.getByRole('button', { name: 'Confirm reviewed change', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('The result is unknown.')
  await expect(amount).toBeDisabled()
  await expect(form.getByRole('button', { name: 'Confirm reviewed change', exact: true })).toHaveCount(0)
  await form.getByRole('button', { name: 'Check saved result', exact: true }).click()
  await expect(form.getByRole('status')).toHaveText('Change confirmed.')
  await expect(amount).toBeEnabled()
})
