import { expect, test } from '@playwright/test'

test.use({ reducedMotion: 'reduce' })

for (const width of [320, 1440]) {
  test(`reporting range preserves drafts and fits a dialog at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/docs/web/reporting')
    const applied = page.locator('[data-applied-period]')
    await expect(applied).toContainText('2026-09-01 to 2026-09-30')
    await page.getByRole('button', { name: 'Reporting period', exact: true }).click()
    await page.getByRole('button', { name: 'Last seven days' }).click()
    await expect(applied).toContainText('2026-09-01 to 2026-09-30')
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(applied).toContainText('2026-09-01 to 2026-09-30')

    await page.getByRole('button', { name: 'Open report settings' }).click()
    const dialog = page.getByRole('dialog', { name: 'Report settings', exact: true })
    await expect(dialog).toBeVisible()
    const trigger = page.getByRole('button', { name: 'Dialog reporting period', exact: true })
    await trigger.click()
    const panel = page.locator('.ui-range-input__panel:visible')
    await expect(panel).toBeVisible()
    const bounds = await panel.boundingBox()
    if (!bounds) throw new Error('Expected range panel bounds')
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
    expect(bounds.y).toBeGreaterThanOrEqual(0)
    expect(bounds.y + bounds.height).toBeLessThanOrEqual(900)
    await page.keyboard.press('Escape')
    await expect(panel).toBeHidden()
    await expect(dialog).toBeVisible()
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.getByRole('button', { name: 'One day', exact: true }).click()
    await page.getByRole('button', { name: 'Apply period', exact: true }).click()
    await expect(applied).toContainText('2026-09-30 to 2026-09-30')
    await page.getByRole('button', { name: 'Close settings', exact: true }).click()
    await expect(dialog).toBeHidden()
    const plot = page.locator('[data-reporting-demo] .ui-chart__plot')
    await plot.focus()
    await expect(plot).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
  })
}

test('loading buttons retain their size and cannot resubmit', async ({ page }) => {
  await page.goto('/docs/web/reporting')
  await page.getByRole('button', { name: 'Open report settings' }).click()
  const save = page.getByRole('button', { name: 'Save report', exact: true })
  await page.evaluate(() => document.fonts.ready)
  await page.getByRole('dialog', { name: 'Report settings', exact: true }).evaluate(async dialog => {
    await Promise.all(dialog.getAnimations().map(animation => animation.finished))
  })
  const before = await save.boundingBox()
  await save.click()
  await expect(save).toBeDisabled()
  await expect(save).toHaveAttribute('aria-busy', 'true')
  const after = await save.boundingBox()
  expect(after?.width).toBe(before?.width)
  expect(after?.height).toBe(before?.height)
})
