import { expect, test } from '@playwright/test'

for (const width of [390, 768, 1440]) for (const theme of ['light', 'dark']) {
  test(`Studio media workspace at ${width}px in ${theme}`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', error => { errors.push(error.message) })
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/docs/studio-media-workspaces')
    const workspace = page.getByRole('region', { name: 'Photo workspace', exact: true })
    await expect(workspace).toBeVisible()
    await workspace.evaluate((element, scheme) => { element.setAttribute('data-lumen-preset', 'studio'); element.setAttribute('data-lumen-scheme', scheme) }, theme)
    const collection = workspace.getByRole('region', { name: 'Illustrative photo collection' })
    await collection.getByRole('button', { name: /^Original landscape/u }).click()
    await expect(collection.getByRole('status')).toHaveText('2 photos selected')
    const move = collection.getByRole('button', { name: 'Move later: Lake landscape' })
    await move.focus()
    await move.press('Enter')
    await expect(move).toBeFocused()
    await expect(collection.locator('li').first()).toContainText('Original landscape')
    const comparison = workspace.locator('.ui-image-comparison input')
    await comparison.focus()
    await comparison.press('ArrowRight')
    const reveal = await comparison.inputValue()
    for (const mode of ['Side by side', 'Original', 'Adjusted']) {
      await workspace.getByRole('button', { name: mode, exact: true }).click()
      await expect(comparison).toBeHidden()
      await expect(comparison).toBeDisabled()
    }
    await workspace.getByRole('button', { name: 'Reveal', exact: true }).click()
    await expect(comparison).toHaveValue(reveal)
    await workspace.getByRole('button', { name: 'Inspect details', exact: true }).click()
    const stage = workspace.locator('[data-ui-media-viewport-stage]')
    await stage.focus()
    await stage.press('+')
    await expect(workspace.locator('[data-ui-media-viewport-status]')).toHaveText('125%')
    await stage.press('ArrowRight')
    await expect(workspace.locator('[data-ui-media-viewport-content]')).toHaveAttribute('style', /translate\(3\.125%/u)
    await stage.press('Home')
    await expect(workspace.locator('[data-ui-media-viewport-status]')).toHaveText('100%')
    const exposure = workspace.getByRole('slider', { name: 'Exposure', exact: true })
    await exposure.focus()
    await exposure.press('ArrowRight')
    await expect(workspace.getByRole('button', { name: 'Reset exposure', exact: true })).toBeEnabled()
    await workspace.getByRole('button', { name: 'Reset exposure', exact: true }).click()
    await expect(exposure).toHaveValue('0')
    await workspace.getByRole('button', { name: 'Prepare preview', exact: true }).click()
    await workspace.getByRole('button', { name: 'Cancel preparation', exact: true }).click()
    await page.waitForTimeout(3200)
    await expect(workspace).toContainText('Preview preparation cancelled.')
    await workspace.getByRole('button', { name: 'Simulate preparation failure', exact: true }).click()
    await workspace.getByRole('button', { name: 'Prepare preview', exact: true }).click()
    await expect(workspace.getByRole('button', { name: 'Retry preparation', exact: true })).toBeVisible()
    await workspace.getByRole('button', { name: 'Simulate preparation failure', exact: true }).click()
    await workspace.getByRole('button', { name: 'Retry preparation', exact: true }).click()
    await expect(workspace).toContainText('Illustrative preview prepared.')
    await workspace.getByRole('button', { name: 'Long Spanish labels', exact: true }).click()
    await page.evaluate(() => { document.documentElement.style.fontSize = '24px' })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    await page.screenshot({ path: testInfo.outputPath(`studio-${width}-${theme}-large-text.png`), fullPage: true })
  })
}
