const extensionName = 'com.santi020k.lumen'
const presetNames = ['default', 'studio', 'glass']
const camel = value => value.replaceAll(/-([a-z])/g, (_, character) => character.toUpperCase())

const validatePresetSettings = (name, preset) => {
  for (const key of ['radiusScale', 'spacingScale', 'borderWidth', 'elevationScale']) {
    if (!Number.isFinite(preset[key]) || preset[key] < 0) {
      throw new Error(`Invalid theme preset ${name}.${key}.`)
    }
  }

  if (!['solid', 'glass'].includes(preset.material)
    || !Array.isArray(preset.fontFamily)
    || preset.fontFamily.length === 0
    || preset.fontFamily.some(value => typeof value !== 'string')) {
    throw new Error(`Invalid material or font family for ${name}.`)
  }
}

const validatePresetColors = (source, name, preset, scheme) => {
  if (!preset.colors?.[scheme]) throw new Error(`Missing ${name}.${scheme} colors.`)

  for (const [role, color] of Object.entries(preset.colors[scheme])) {
    if (!Object.hasOwn(source.color[scheme], role)
      || !/^#[\da-f]{6}$/i.test(color.hex)
      || typeof color.css !== 'string') {
      throw new Error(`Invalid ${name}.${scheme}.${role} color.`)
    }
  }
}

export const readThemePresets = source => {
  const presets = source.$extensions?.[extensionName]?.themePresets

  if (!presets || Object.keys(presets).join(',') !== presetNames.join(',')) {
    throw new Error('Theme presets must define default, studio and glass in order.')
  }

  for (const [name, preset] of Object.entries(presets)) {
    validatePresetSettings(name, preset)

    validatePresetColors(source, name, preset, 'light')

    validatePresetColors(source, name, preset, 'dark')
  }

  return presets
}

export const generatePresetTypeScript = presets => {
  const definitions = Object.fromEntries(Object.entries(presets).map(([name, preset]) => [name, {
    ...preset,
    colors: Object.fromEntries(Object.entries(preset.colors).map(([scheme, colors]) => [scheme,
      Object.fromEntries(Object.entries(colors).map(([role, color]) => [camel(role), color.hex]))
    ])),
    cssColors: Object.fromEntries(Object.entries(preset.colors).map(([scheme, colors]) => [scheme,
      Object.fromEntries(Object.entries(colors).map(([role, color]) => [role, color.css]))
    ]))
  }]))

  return `/* This file is generated by scripts/generate-platform-tokens.mjs. */\n\nexport const lumenThemePresetDefinitions = ${JSON.stringify(definitions, null, 2)} as const\n\nexport type LumenThemePreset = keyof typeof lumenThemePresetDefinitions\nexport type LumenSurfaceMaterial = 'solid' | 'glass'\n`
}

const fullColors = (source, preset, scheme) => Object.entries(source.color[scheme])
  .filter(([role]) => !role.startsWith('$'))
  .map(([role, token]) => [role, preset.colors[scheme][role]?.hex ?? token.$value])

export const generatePresetSwift = (source, presets) => {
  const palettes = Object.entries(presets).flatMap(([name, preset]) => ['light', 'dark'].map(scheme => {
    const args = fullColors(source, preset, scheme).map(([role, hex]) => {
      const values = [1, 3, 5].map(index => (Number.parseInt(hex.slice(index, index + 2), 16) / 255).toFixed(6))

      return `        ${camel(role)}: Color(red: ${values[0]}, green: ${values[1]}, blue: ${values[2]})`
    }).join(',\n')

    return `    public static let ${name}${scheme === 'light' ? 'Light' : 'Dark'} = LumenColorPalette(\n${args}\n    )`
  })).join('\n\n')

  const appearances = Object.entries(presets).map(([name, preset]) =>
    `        case .${name === 'default' ? '`default`' : name}: LumenAppearance(radiusScale: ${preset.radiusScale}, spacingScale: ${preset.spacingScale}, borderWidth: ${preset.borderWidth}, elevationScale: ${preset.elevationScale}, material: .${preset.material})`
  ).join('\n')

  return `// This file is generated by scripts/generate-platform-tokens.mjs.\nimport SwiftUI\n\npublic enum LumenThemePreset: String, CaseIterable, Sendable {\n    case \`default\`\n    case studio\n    case glass\n\n    public var appearance: LumenAppearance {\n        switch self {\n${appearances}\n        }\n    }\n\n    public func colors(for scheme: LumenColorScheme) -> LumenColorPalette {\n        switch (self, scheme) {\n${Object.keys(presets).flatMap(name => ['light', 'dark'].map(scheme => `        case (.${name === 'default' ? '`default`' : name}, .${scheme}): LumenPresetColors.${name}${scheme === 'light' ? 'Light' : 'Dark'}`)).join('\n')}\n        }\n    }\n}\n\npublic enum LumenPresetColors {\n${palettes}\n}\n`
}

export const generatePresetKotlin = (source, presets) => {
  const palettes = Object.entries(presets).flatMap(([name, preset]) => ['light', 'dark'].map(scheme => {
    const args = fullColors(source, preset, scheme).map(([role, hex]) =>
      `        ${camel(role)} = Color(0xFF${hex.slice(1)})`
    ).join(',\n')

    return `    val ${name[0].toUpperCase() + name.slice(1)}${scheme === 'light' ? 'Light' : 'Dark'} = LumenColorPalette(\n${args}\n    )`
  })).join('\n\n')

  return `// This file is generated by scripts/generate-platform-tokens.mjs.\npackage com.santi020k.lumen\n\nimport androidx.compose.ui.graphics.Color\n\nenum class LumenThemePreset {\n    Default, Studio, Glass;\n\n    val appearance: LumenAppearance\n        get() = when (this) {\n${Object.entries(presets).map(([name, preset]) => `            ${name[0].toUpperCase() + name.slice(1)} -> LumenAppearance(radiusScale = ${preset.radiusScale}f, spacingScale = ${preset.spacingScale}f, borderWidth = ${preset.borderWidth}f, elevationScale = ${preset.elevationScale}f, material = LumenSurfaceMaterial.${preset.material[0].toUpperCase() + preset.material.slice(1)})`).join('\n')}\n        }\n\n    fun colors(isDark: Boolean): LumenColorPalette = when (this) {\n${Object.keys(presets).map(name => `        ${name[0].toUpperCase() + name.slice(1)} -> if (isDark) LumenPresetColors.${name[0].toUpperCase() + name.slice(1)}Dark else LumenPresetColors.${name[0].toUpperCase() + name.slice(1)}Light`).join('\n')}\n    }\n}\n\nobject LumenPresetColors {\n${palettes}\n}\n`
}

export const generatePresetCss = (source, presets) => {
  const blocks = Object.entries(presets).flatMap(([name, preset]) => ['light', 'dark'].map(scheme => {
    const selector = `[data-lumen-preset="${name}"]`

    const selectors = scheme === 'dark'
      ? [`:where([data-theme="dark"], [data-theme="lumen-dark"]) ${selector}:not([data-lumen-scheme="light"], [data-theme="light"], [data-theme="lumen-light"])`, `${selector}[data-lumen-scheme="dark"]`, `${selector}[data-theme="dark"]:not([data-lumen-scheme="light"])`, `${selector}[data-theme="lumen-dark"]:not([data-lumen-scheme="light"])`]
      : [selector, `${selector}[data-lumen-scheme="light"]`]

    const colors = Object.entries(source.color[scheme])
      .filter(([role]) => !role.startsWith('$'))
      .map(([role, token]) => `  --${role}: ${preset.colors[scheme][role]?.css ?? token.$extensions[extensionName].cssValue};`)

    const spacing = Object.entries(source.space).filter(([name]) => !name.startsWith('$')).map(([name, token]) => `  --ui-space-${name}: ${token.$value.value / 16 * preset.spacingScale}rem;`)
    const font = preset.fontFamily.map(family => ['system-ui', 'sans-serif'].includes(family) ? family : JSON.stringify(family)).join(', ')

    return `${selectors.join(',\n')} {\n  color-scheme: ${scheme};\n${colors.join('\n')}\n${spacing.join('\n')}\n  --ui-radius-sm: ${source.radius.sm.$value.value / 16 * preset.radiusScale}rem;\n  --ui-radius: ${source.radius.md.$value.value / 16 * preset.radiusScale}rem;\n  --ui-radius-lg: ${source.radius.lg.$value.value / 16 * preset.radiusScale}rem;\n  --ui-border-width: ${preset.borderWidth}px;\n  --ui-font: ${font};\n${Object.entries(preset.effects[scheme]).map(([key, value]) => `  --${key}: ${value};`).join('\n')}\n}`
  }))

  return `/* BEGIN:generated-theme-presets */\n@layer lumen.tokens {\n${blocks.join('\n\n')}\n}\n/* END:generated-theme-presets */`
}
