// This file is generated by scripts/generate-platform-graphics.mjs.
package com.santi020k.lumen

internal sealed interface LumenIllustrationElement {
    data class Circle(val cx: Float, val cy: Float, val radius: Float) : LumenIllustrationElement
    data class Line(val points: List<Float>) : LumenIllustrationElement
    data class Polygon(val points: List<Float>) : LumenIllustrationElement
    data class Polyline(val points: List<Float>) : LumenIllustrationElement
    data class RoundedRect(
        val x: Float,
        val y: Float,
        val width: Float,
        val height: Float,
        val radius: Float
    ) : LumenIllustrationElement
}

internal val lumenIllustrationArtwork = mapOf(
    LumenIllustrationVariant.Empty to listOf(
        LumenIllustrationElement.Polygon(listOf(32f, 48f, 88f, 48f, 81f, 83f, 39f, 83f)),
        LumenIllustrationElement.Polyline(listOf(43f, 48f, 49f, 36f, 71f, 36f, 77f, 48f)),
        LumenIllustrationElement.Line(listOf(47f, 66f, 73f, 66f))
    ),
    LumenIllustrationVariant.Success to listOf(
        LumenIllustrationElement.Circle(60f, 60f, 28f),
        LumenIllustrationElement.Polyline(listOf(45f, 60f, 55f, 70f, 76f, 47f))
    ),
    LumenIllustrationVariant.Error to listOf(
        LumenIllustrationElement.Circle(60f, 60f, 28f),
        LumenIllustrationElement.Line(listOf(49f, 49f, 71f, 71f)),
        LumenIllustrationElement.Line(listOf(71f, 49f, 49f, 71f))
    ),
    LumenIllustrationVariant.Offline to listOf(
        LumenIllustrationElement.RoundedRect(24f, 45f, 72f, 35f, 18f),
        LumenIllustrationElement.Line(listOf(30f, 30f, 90f, 90f))
    )
)
