// This file is generated by scripts/generate-platform-tokens.mjs.
package com.santi020k.lumen

import androidx.compose.ui.graphics.Color

enum class LumenThemePreset {
    Default, Studio, Glass;

    val appearance: LumenAppearance
        get() = when (this) {
            Default -> LumenAppearance(radiusScale = 1f, spacingScale = 1f, borderWidth = 1f, elevationScale = 1f, material = LumenSurfaceMaterial.Solid)
            Studio -> LumenAppearance(radiusScale = 0.6f, spacingScale = 1f, borderWidth = 1f, elevationScale = 0f, material = LumenSurfaceMaterial.Solid)
            Glass -> LumenAppearance(radiusScale = 1.4f, spacingScale = 1f, borderWidth = 1f, elevationScale = 1f, material = LumenSurfaceMaterial.Glass)
        }

    fun colors(isDark: Boolean): LumenColorPalette = when (this) {
        Default -> if (isDark) LumenPresetColors.DefaultDark else LumenPresetColors.DefaultLight
        Studio -> if (isDark) LumenPresetColors.StudioDark else LumenPresetColors.StudioLight
        Glass -> if (isDark) LumenPresetColors.GlassDark else LumenPresetColors.GlassLight
    }
}

object LumenPresetColors {
    val DefaultLight = LumenColorPalette(
        canvas = Color(0xFFF9FAFB),
        surface = Color(0xFFFFFFFF),
        surfaceMuted = Color(0xFFEFF2F5),
        surfaceStrong = Color(0xFFDBE0E6),
        line = Color(0xFFCFD5DD),
        ink = Color(0xFF161D27),
        inkSoft = Color(0xFF4D5766),
        inkMuted = Color(0xFF737D8C),
        brand = Color(0xFF0369A0),
        brandSolid = Color(0xFF035C8C),
        brandSoft = Color(0xFFDEF0F8),
        onBrand = Color(0xFFFFFFFF),
        accent = Color(0xFF13967E),
        success = Color(0xFF16A249),
        warning = Color(0xFFF59F0A),
        danger = Color(0xFFEF4343),
        onDanger = Color(0xFF000000)
    )

    val DefaultDark = LumenColorPalette(
        canvas = Color(0xFF101219),
        surface = Color(0xFF171A21),
        surfaceMuted = Color(0xFF20242C),
        surfaceStrong = Color(0xFF303540),
        line = Color(0xFF393F4C),
        ink = Color(0xFFF3F5F7),
        inkSoft = Color(0xFFBCC3CD),
        inkMuted = Color(0xFF949CA8),
        brand = Color(0xFF29B4F5),
        brandSolid = Color(0xFF087AAF),
        brandSoft = Color(0xFF07354B),
        onBrand = Color(0xFFFFFFFF),
        accent = Color(0xFF1AC19A),
        success = Color(0xFF24C25E),
        warning = Color(0xFFF6A823),
        danger = Color(0xFFF15B5B),
        onDanger = Color(0xFF101219)
    )

    val StudioLight = LumenColorPalette(
        canvas = Color(0xFFFFFFFF),
        surface = Color(0xFFFFFFFF),
        surfaceMuted = Color(0xFFF4F4F4),
        surfaceStrong = Color(0xFFE8E8E8),
        line = Color(0xFFE5E5E5),
        ink = Color(0xFF171717),
        inkSoft = Color(0xFF525252),
        inkMuted = Color(0xFF737373),
        brand = Color(0xFF171717),
        brandSolid = Color(0xFF171717),
        brandSoft = Color(0xFFEBEBEB),
        onBrand = Color(0xFFFFFFFF),
        accent = Color(0xFF171717),
        success = Color(0xFF16A249),
        warning = Color(0xFFF59F0A),
        danger = Color(0xFFEF4343),
        onDanger = Color(0xFF000000)
    )

    val StudioDark = LumenColorPalette(
        canvas = Color(0xFF111111),
        surface = Color(0xFF111111),
        surfaceMuted = Color(0xFF1C1C1C),
        surfaceStrong = Color(0xFF303030),
        line = Color(0xFF383838),
        ink = Color(0xFFF5F5F5),
        inkSoft = Color(0xFFCCCCCC),
        inkMuted = Color(0xFFA3A3A3),
        brand = Color(0xFFF5F5F5),
        brandSolid = Color(0xFFF5F5F5),
        brandSoft = Color(0xFF242424),
        onBrand = Color(0xFF111111),
        accent = Color(0xFFF5F5F5),
        success = Color(0xFF24C25E),
        warning = Color(0xFFF6A823),
        danger = Color(0xFFF15B5B),
        onDanger = Color(0xFF101219)
    )

    val GlassLight = LumenColorPalette(
        canvas = Color(0xFFF9FAFB),
        surface = Color(0xFFFFFFFF),
        surfaceMuted = Color(0xFFEFF2F5),
        surfaceStrong = Color(0xFFDBE0E6),
        line = Color(0xFFCFD5DD),
        ink = Color(0xFF161D27),
        inkSoft = Color(0xFF4D5766),
        inkMuted = Color(0xFF737D8C),
        brand = Color(0xFF0369A0),
        brandSolid = Color(0xFF035C8C),
        brandSoft = Color(0xFFDEF0F8),
        onBrand = Color(0xFFFFFFFF),
        accent = Color(0xFF13967E),
        success = Color(0xFF16A249),
        warning = Color(0xFFF59F0A),
        danger = Color(0xFFEF4343),
        onDanger = Color(0xFF000000)
    )

    val GlassDark = LumenColorPalette(
        canvas = Color(0xFF101219),
        surface = Color(0xFF171A21),
        surfaceMuted = Color(0xFF20242C),
        surfaceStrong = Color(0xFF303540),
        line = Color(0xFF393F4C),
        ink = Color(0xFFF3F5F7),
        inkSoft = Color(0xFFBCC3CD),
        inkMuted = Color(0xFF949CA8),
        brand = Color(0xFF29B4F5),
        brandSolid = Color(0xFF087AAF),
        brandSoft = Color(0xFF07354B),
        onBrand = Color(0xFFFFFFFF),
        accent = Color(0xFF1AC19A),
        success = Color(0xFF24C25E),
        warning = Color(0xFFF6A823),
        danger = Color(0xFFF15B5B),
        onDanger = Color(0xFF101219)
    )
}
