// This file is generated by scripts/generate-platform-tokens.mjs.
import SwiftUI

public enum LumenThemePreset: String, CaseIterable, Sendable {
    case `default`
    case studio
    case glass

    public var appearance: LumenAppearance {
        switch self {
        case .`default`: LumenAppearance(radiusScale: 1, spacingScale: 1, borderWidth: 1, elevationScale: 1, material: .solid)
        case .studio: LumenAppearance(radiusScale: 0.6, spacingScale: 1, borderWidth: 1, elevationScale: 0, material: .solid)
        case .glass: LumenAppearance(radiusScale: 1.4, spacingScale: 1, borderWidth: 1, elevationScale: 1, material: .glass)
        }
    }

    public func colors(for scheme: LumenColorScheme) -> LumenColorPalette {
        switch (self, scheme) {
        case (.`default`, .light): LumenPresetColors.defaultLight
        case (.`default`, .dark): LumenPresetColors.defaultDark
        case (.studio, .light): LumenPresetColors.studioLight
        case (.studio, .dark): LumenPresetColors.studioDark
        case (.glass, .light): LumenPresetColors.glassLight
        case (.glass, .dark): LumenPresetColors.glassDark
        }
    }
}

public enum LumenPresetColors {
    public static let defaultLight = LumenColorPalette(
        canvas: Color(red: 0.976471, green: 0.980392, blue: 0.984314),
        surface: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        surfaceMuted: Color(red: 0.937255, green: 0.949020, blue: 0.960784),
        surfaceStrong: Color(red: 0.858824, green: 0.878431, blue: 0.901961),
        line: Color(red: 0.811765, green: 0.835294, blue: 0.866667),
        ink: Color(red: 0.086275, green: 0.113725, blue: 0.152941),
        inkSoft: Color(red: 0.301961, green: 0.341176, blue: 0.400000),
        inkMuted: Color(red: 0.450980, green: 0.490196, blue: 0.549020),
        brand: Color(red: 0.011765, green: 0.411765, blue: 0.627451),
        brandSolid: Color(red: 0.011765, green: 0.360784, blue: 0.549020),
        brandSoft: Color(red: 0.870588, green: 0.941176, blue: 0.972549),
        onBrand: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        accent: Color(red: 0.074510, green: 0.588235, blue: 0.494118),
        success: Color(red: 0.086275, green: 0.635294, blue: 0.286275),
        warning: Color(red: 0.960784, green: 0.623529, blue: 0.039216),
        danger: Color(red: 0.937255, green: 0.262745, blue: 0.262745),
        onDanger: Color(red: 0.000000, green: 0.000000, blue: 0.000000)
    )

    public static let defaultDark = LumenColorPalette(
        canvas: Color(red: 0.062745, green: 0.070588, blue: 0.098039),
        surface: Color(red: 0.090196, green: 0.101961, blue: 0.129412),
        surfaceMuted: Color(red: 0.125490, green: 0.141176, blue: 0.172549),
        surfaceStrong: Color(red: 0.188235, green: 0.207843, blue: 0.250980),
        line: Color(red: 0.223529, green: 0.247059, blue: 0.298039),
        ink: Color(red: 0.952941, green: 0.960784, blue: 0.968627),
        inkSoft: Color(red: 0.737255, green: 0.764706, blue: 0.803922),
        inkMuted: Color(red: 0.580392, green: 0.611765, blue: 0.658824),
        brand: Color(red: 0.160784, green: 0.705882, blue: 0.960784),
        brandSolid: Color(red: 0.031373, green: 0.478431, blue: 0.686275),
        brandSoft: Color(red: 0.027451, green: 0.207843, blue: 0.294118),
        onBrand: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        accent: Color(red: 0.101961, green: 0.756863, blue: 0.603922),
        success: Color(red: 0.141176, green: 0.760784, blue: 0.368627),
        warning: Color(red: 0.964706, green: 0.658824, blue: 0.137255),
        danger: Color(red: 0.945098, green: 0.356863, blue: 0.356863),
        onDanger: Color(red: 0.062745, green: 0.070588, blue: 0.098039)
    )

    public static let studioLight = LumenColorPalette(
        canvas: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        surface: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        surfaceMuted: Color(red: 0.956863, green: 0.956863, blue: 0.956863),
        surfaceStrong: Color(red: 0.909804, green: 0.909804, blue: 0.909804),
        line: Color(red: 0.898039, green: 0.898039, blue: 0.898039),
        ink: Color(red: 0.090196, green: 0.090196, blue: 0.090196),
        inkSoft: Color(red: 0.321569, green: 0.321569, blue: 0.321569),
        inkMuted: Color(red: 0.450980, green: 0.450980, blue: 0.450980),
        brand: Color(red: 0.090196, green: 0.090196, blue: 0.090196),
        brandSolid: Color(red: 0.090196, green: 0.090196, blue: 0.090196),
        brandSoft: Color(red: 0.921569, green: 0.921569, blue: 0.921569),
        onBrand: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        accent: Color(red: 0.090196, green: 0.090196, blue: 0.090196),
        success: Color(red: 0.086275, green: 0.635294, blue: 0.286275),
        warning: Color(red: 0.960784, green: 0.623529, blue: 0.039216),
        danger: Color(red: 0.937255, green: 0.262745, blue: 0.262745),
        onDanger: Color(red: 0.000000, green: 0.000000, blue: 0.000000)
    )

    public static let studioDark = LumenColorPalette(
        canvas: Color(red: 0.066667, green: 0.066667, blue: 0.066667),
        surface: Color(red: 0.066667, green: 0.066667, blue: 0.066667),
        surfaceMuted: Color(red: 0.109804, green: 0.109804, blue: 0.109804),
        surfaceStrong: Color(red: 0.188235, green: 0.188235, blue: 0.188235),
        line: Color(red: 0.219608, green: 0.219608, blue: 0.219608),
        ink: Color(red: 0.960784, green: 0.960784, blue: 0.960784),
        inkSoft: Color(red: 0.800000, green: 0.800000, blue: 0.800000),
        inkMuted: Color(red: 0.639216, green: 0.639216, blue: 0.639216),
        brand: Color(red: 0.960784, green: 0.960784, blue: 0.960784),
        brandSolid: Color(red: 0.960784, green: 0.960784, blue: 0.960784),
        brandSoft: Color(red: 0.141176, green: 0.141176, blue: 0.141176),
        onBrand: Color(red: 0.066667, green: 0.066667, blue: 0.066667),
        accent: Color(red: 0.960784, green: 0.960784, blue: 0.960784),
        success: Color(red: 0.141176, green: 0.760784, blue: 0.368627),
        warning: Color(red: 0.964706, green: 0.658824, blue: 0.137255),
        danger: Color(red: 0.945098, green: 0.356863, blue: 0.356863),
        onDanger: Color(red: 0.062745, green: 0.070588, blue: 0.098039)
    )

    public static let glassLight = LumenColorPalette(
        canvas: Color(red: 0.976471, green: 0.980392, blue: 0.984314),
        surface: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        surfaceMuted: Color(red: 0.937255, green: 0.949020, blue: 0.960784),
        surfaceStrong: Color(red: 0.858824, green: 0.878431, blue: 0.901961),
        line: Color(red: 0.811765, green: 0.835294, blue: 0.866667),
        ink: Color(red: 0.086275, green: 0.113725, blue: 0.152941),
        inkSoft: Color(red: 0.301961, green: 0.341176, blue: 0.400000),
        inkMuted: Color(red: 0.450980, green: 0.490196, blue: 0.549020),
        brand: Color(red: 0.011765, green: 0.411765, blue: 0.627451),
        brandSolid: Color(red: 0.011765, green: 0.360784, blue: 0.549020),
        brandSoft: Color(red: 0.870588, green: 0.941176, blue: 0.972549),
        onBrand: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        accent: Color(red: 0.074510, green: 0.588235, blue: 0.494118),
        success: Color(red: 0.086275, green: 0.635294, blue: 0.286275),
        warning: Color(red: 0.960784, green: 0.623529, blue: 0.039216),
        danger: Color(red: 0.937255, green: 0.262745, blue: 0.262745),
        onDanger: Color(red: 0.000000, green: 0.000000, blue: 0.000000)
    )

    public static let glassDark = LumenColorPalette(
        canvas: Color(red: 0.062745, green: 0.070588, blue: 0.098039),
        surface: Color(red: 0.090196, green: 0.101961, blue: 0.129412),
        surfaceMuted: Color(red: 0.125490, green: 0.141176, blue: 0.172549),
        surfaceStrong: Color(red: 0.188235, green: 0.207843, blue: 0.250980),
        line: Color(red: 0.223529, green: 0.247059, blue: 0.298039),
        ink: Color(red: 0.952941, green: 0.960784, blue: 0.968627),
        inkSoft: Color(red: 0.737255, green: 0.764706, blue: 0.803922),
        inkMuted: Color(red: 0.580392, green: 0.611765, blue: 0.658824),
        brand: Color(red: 0.160784, green: 0.705882, blue: 0.960784),
        brandSolid: Color(red: 0.031373, green: 0.478431, blue: 0.686275),
        brandSoft: Color(red: 0.027451, green: 0.207843, blue: 0.294118),
        onBrand: Color(red: 1.000000, green: 1.000000, blue: 1.000000),
        accent: Color(red: 0.101961, green: 0.756863, blue: 0.603922),
        success: Color(red: 0.141176, green: 0.760784, blue: 0.368627),
        warning: Color(red: 0.964706, green: 0.658824, blue: 0.137255),
        danger: Color(red: 0.945098, green: 0.356863, blue: 0.356863),
        onDanger: Color(red: 0.062745, green: 0.070588, blue: 0.098039)
    )
}
